name: Context Examples

on: ['push']

jobs:
    my-context:
        runs-on: ubuntu-latest
        steps:
            - name: "My setup"
              run: echo "Hello! $MY_ACTION $MY_ACTOR"
              env:
                MY_ACTION: ${{github.action}}
                MY_ACTOR: ${{github.actor}}