name: "Dep job examples"

on: ["push"]
jobs:
    job2:
        runs-on: ubuntu-latest
        needs: ["job1"]
        steps:
            - name: "job 2"
              run: echo "World"

    job1:
        runs-on: ubuntu-latest
        steps:
            - name: "job 1"
              run: echo "Hello "
